title: Stacey Kay # your name (or website title) here
logo: "https://github.com/heystaceykay/heystaceykay.github.io/blob/master/images/hskLogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  in search of some web to develop.
  <br><br>
  <a href="https://www.linkedin.com/in/heystaceykay/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
